c iongeo.inc
      COMMON/COORD/TETA1(NJP1,NK2P1),PHI1(NJP1,NK2P1),
     $		x1ion(njp1,nk2p1),y1ion(njp1,nk2p1),
     1             TETA2(NJP1,NK2P3),PHI2(NJP1,NK2P3),
     2		   x2ion(njp1,nk2p3),y2ion(njp1,nk2p3),
     1             TETAhf(NJ,NK2),PHIhf(NJ,NK2),
     2		   xhfion(nj,nk2),yhfion(nj,nk2)
      COMMON/COEF/Apeder(njp1,nk2p3,kk,kk),Ahall(njp1,nk2p3,kk,kk)
     $			,aj(njp1,nk2p3,kk)
